# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('V', 'Hombre'), ('M', 'Mujer')], default='M', max_length=1),
        ),
    ]
